
// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {html, css, LitElement, TemplateResult} from 'lit-element';

import {AmfHelperMixin} from '@api-components/amf-helper-mixin/amf-helper-mixin.js';

export {ApiAuthorization};

/**
 * An element that renders various authorization methods.
 *
 * ## Development
 *
 * The element mixes in multimple mixins from `src/` directory.
 * Each mixin support an authorization method. When selection change (the `type`
 * property) a render function from correcponding mixin is called.
 */
declare class ApiAuthorization extends AmfHelperMixin(LitElement) {
  readonly styles: any;
  /**
   * A security model generated by the AMF parser.
   */
  security: Array<Object>;

  constructor();
  connectedCallback(): void;
  render(): any;

}
